# Generated by Django 3.2.7 on 2021-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anno', '0003_auto_20210929_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
